import type {
  AiCapability,
  AiProvider,
  AiProviderAvailability,
  AiProviderKind,
  AiProviderStatus
} from '../types/aiProviderTypes';
import type { AiRequest } from '../types/aiRequestTypes';
import type { AiResponse } from '../types/aiResponseTypes';

export interface MockProviderConfig {
  readonly id: string;
  readonly name?: string;
  readonly kind?: AiProviderKind;
  readonly capabilities?: readonly AiCapability[];
  readonly availability?: AiProviderAvailability;
  readonly statusMessage?: string;
  readonly fail?: boolean;
}

/**
 * Test helper for constructing mock AiProviders with controllable capabilities and behavior.
 */
export function createMockProvider(config: MockProviderConfig): AiProvider {
  const providerId = config.id;
  const providerName = config.name ?? config.id;
  const providerKind: AiProviderKind = config.kind ?? 'LOCAL_RULES';
  const availability: AiProviderAvailability = config.availability ?? 'AVAILABLE';

  const defaultCapabilities: readonly AiCapability[] = Object.freeze([
    'CHART_SYNTHESIS',
    'CAREER',
    'WEALTH',
    'DASHA',
    'LIFE_THEMES',
    'LIFE_ANALYSIS',
    'STRUCTURED_OUTPUT'
  ]);

  const capabilities = Object.freeze(config.capabilities ?? defaultCapabilities);

  return Object.freeze({
    identity: Object.freeze({
      id: providerId,
      name: providerName,
      kind: providerKind,
      version: '1.0.0'
    }),
    capabilities,
    getStatus(): AiProviderStatus {
      return Object.freeze({
        availability,
        message: config.statusMessage
      });
    },
    async generate(request: AiRequest): Promise<AiResponse> {
      if (config.fail) {
        throw new Error(`${providerId} failed`);
      }

      return Object.freeze({
        requestId: request.requestId,
        content: `Mock content generated by ${providerName}`,
        structuredOutput:
          request.responseFormat === 'STRUCTURED'
            ? Object.freeze({ mock: true, provider: providerId, task: request.task })
            : undefined,
        format: request.responseFormat,
        warnings: Object.freeze([]),
        metadata: Object.freeze({
          provider: providerId,
          model: 'TEST'
        })
      });
    }
  });
}
